import type { Metadata } from "next";
import "./../styles/globals.css";
import Navbar from "@/components/organism/Navbar";
import Footer from "@/components/organism/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased flex flex-col `}>
        <nav className="fixed w-full z-50">
          <Navbar />
        </nav>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
